# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/conrtollernewdynamic2/conrtollernewdynamic2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conrtollernewdynamic2 || ORIG_REF_NAME==conrtollernewdynamic2}]

# IP: bd/conrtollernewdynamic2/ip/conrtollernewdynamic2_processing_system7_0_0/conrtollernewdynamic2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conrtollernewdynamic2_processing_system7_0_0 || ORIG_REF_NAME==conrtollernewdynamic2_processing_system7_0_0}]

# IP: bd/conrtollernewdynamic2/ip/conrtollernewdynamic2_newdynamics2_0_0/conrtollernewdynamic2_newdynamics2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conrtollernewdynamic2_newdynamics2_0_0 || ORIG_REF_NAME==conrtollernewdynamic2_newdynamics2_0_0}]

# IP: bd/conrtollernewdynamic2/ip/conrtollernewdynamic2_ps7_0_axi_periph_0/conrtollernewdynamic2_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conrtollernewdynamic2_ps7_0_axi_periph_0 || ORIG_REF_NAME==conrtollernewdynamic2_ps7_0_axi_periph_0}]

# IP: bd/conrtollernewdynamic2/ip/conrtollernewdynamic2_rst_ps7_0_100M_0/conrtollernewdynamic2_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conrtollernewdynamic2_rst_ps7_0_100M_0 || ORIG_REF_NAME==conrtollernewdynamic2_rst_ps7_0_100M_0}]

# IP: bd/conrtollernewdynamic2/ip/conrtollernewdynamic2_auto_pc_0/conrtollernewdynamic2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conrtollernewdynamic2_auto_pc_0 || ORIG_REF_NAME==conrtollernewdynamic2_auto_pc_0}]

# XDC: bd/conrtollernewdynamic2/conrtollernewdynamic2_ooc.xdc
